#!/bin/bash
cd /tmp # Where to download ccache
time aria2c https://weathered-dawn-c550.apxd.workers.dev/styxizsex2.tar.gz
echo "dl done"
time tar xf styxizsex2.tar.gz
echo "unzip done"
find styxizsex2.tar.gz -delete
