#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/StyxProject/manifest
BRANCH=R  

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "AP-XD"
git config --global user.email "arkamtg.pramanik@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/AP-XD/android_vendor_xiaomi_surya vendor/xiaomi/surya
git clone https://github.com/AP-XD/android_kernel_xiaomi_surya kernel/xiaomi/surya
git clone https://github.com/AP-XD/android_device_xiaomi_surya device/xiaomi/surya

cd /tmp/rom
